// src/main/webapp/app/entities/advice/detail/advice-detail.component.ts
import { Component, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatePipe, FormatMediumDatetimePipe } from 'app/shared/date';
import { IAdvice } from '../advice.model';

@Component({
  standalone: true,
  selector: 'stp-advice-detail',
  templateUrl: './advice-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class AdviceDetailComponent {
  advice = input<IAdvice | null>(null);

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (advice(); as adviceRef) {
      <div>
        <h2 data-cy="adviceDetailsHeading"><span stpTranslate="simulatorApp.advice.detail.title">Advice</span></h2>

        <hr />

        <stp-alert-error></stp-alert-error>

        <stp-alert></stp-alert>

        <dl class="row-md jh-entity-details">
          <dt><span stpTranslate="global.field.id">ID</span></dt>
          <dd>
            <span>{{ adviceRef.id }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.advice.code">Code</span></dt>
          <dd>
            <span>{{ adviceRef.code }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.advice.name">Name</span></dt>
          <dd>
            <span>{{ adviceRef.name }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.advice.merchant">Merchant</span></dt>
          <dd>
            @if (advice()!.merchant) {
              <div>
                <a [routerLink]="['/merchant', advice()!.merchant?.id, 'view']">{{ adviceRef.merchant?.id }}</a>
              </div>
            }
          </dd>
          <dt><span stpTranslate="simulatorApp.advice.acquirer">Acquirer</span></dt>
          <dd>
            @if (advice()!.acquirer) {
              <div>
                <a [routerLink]="['/acquirer', advice()!.acquirer?.id, 'view']">{{ adviceRef.acquirer?.id }}</a>
              </div>
            }
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span stpTranslate="entity.action.back">Volver</span>
        </button>

        <button type="button" [routerLink]="['/advice', adviceRef.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span stpTranslate="entity.action.edit">Editar</span>
        </button>
      </div>
    }
  </div>
</div>

// src/main/webapp/app/entities/advice/advice-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Col, Row } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './advice.reducer';

export const AdviceDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const adviceEntity = useAppSelector(state => state.advice.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="adviceDetailsHeading">
          <Translate contentKey="simulatorApp.advice.detail.title">Advice</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{adviceEntity.id}</dd>
          <dt>
            <span id="code">
              <Translate contentKey="simulatorApp.advice.code">Code</Translate>
            </span>
          </dt>
          <dd>{adviceEntity.code}</dd>
          <dt>
            <span id="name">
              <Translate contentKey="simulatorApp.advice.name">Name</Translate>
            </span>
          </dt>
          <dd>{adviceEntity.name}</dd>
          <dt>
            <Translate contentKey="simulatorApp.advice.merchant">Merchant</Translate>
          </dt>
          <dd>{adviceEntity.merchant ? adviceEntity.merchant.id : ''}</dd>
          <dt>
            <Translate contentKey="simulatorApp.advice.acquirer">Acquirer</Translate>
          </dt>
          <dd>{adviceEntity.acquirer ? adviceEntity.acquirer.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/advice" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/advice/${adviceEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default AdviceDetail;
