// src/main/webapp/app/entities/credit-card/detail/credit-card-detail.component.ts
import { Component, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatePipe, FormatMediumDatetimePipe } from 'app/shared/date';
import { ICreditCard } from '../credit-card.model';

@Component({
  standalone: true,
  selector: 'stp-credit-card-detail',
  templateUrl: './credit-card-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class CreditCardDetailComponent {
  creditCard = input<ICreditCard | null>(null);

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (creditCard(); as creditCardRef) {
      <div>
        <h2 data-cy="creditCardDetailsHeading"><span stpTranslate="simulatorApp.creditCard.detail.title">Credit Card</span></h2>

        <hr />

        <stp-alert-error></stp-alert-error>

        <stp-alert></stp-alert>

        <dl class="row-md jh-entity-details">
          <dt><span stpTranslate="global.field.id">ID</span></dt>
          <dd>
            <span>{{ creditCardRef.id }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.creditCard.maxLimit">Max Limit</span></dt>
          <dd>
            <span>{{ creditCardRef.maxLimit }}</span>
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span stpTranslate="entity.action.back">Volver</span>
        </button>

        <button type="button" [routerLink]="['/credit-card', creditCardRef.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span stpTranslate="entity.action.edit">Editar</span>
        </button>
      </div>
    }
  </div>
</div>

// src/main/webapp/app/entities/credit-card/credit-card-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Col, Row } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './credit-card.reducer';

export const CreditCardDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const creditCardEntity = useAppSelector(state => state.creditCard.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="creditCardDetailsHeading">
          <Translate contentKey="simulatorApp.creditCard.detail.title">CreditCard</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{creditCardEntity.id}</dd>
          <dt>
            <span id="maxLimit">
              <Translate contentKey="simulatorApp.creditCard.maxLimit">Max Limit</Translate>
            </span>
          </dt>
          <dd>{creditCardEntity.maxLimit}</dd>
        </dl>
        <Button tag={Link} to="/credit-card" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/credit-card/${creditCardEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default CreditCardDetail;
