// src/main/webapp/app/entities/message-type-indicator/message-type-indicator-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Col, Row } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './message-type-indicator.reducer';

export const MessageTypeIndicatorDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const messageTypeIndicatorEntity = useAppSelector(state => state.messageTypeIndicator.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="messageTypeIndicatorDetailsHeading">
          <Translate contentKey="simulatorApp.messageTypeIndicator.detail.title">MessageTypeIndicator</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{messageTypeIndicatorEntity.id}</dd>
          <dt>
            <span id="name">
              <Translate contentKey="simulatorApp.messageTypeIndicator.name">Name</Translate>
            </span>
          </dt>
          <dd>{messageTypeIndicatorEntity.name}</dd>
          <dt>
            <span id="code">
              <Translate contentKey="simulatorApp.messageTypeIndicator.code">Code</Translate>
            </span>
          </dt>
          <dd>{messageTypeIndicatorEntity.code}</dd>
        </dl>
        <Button tag={Link} to="/message-type-indicator" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/message-type-indicator/${messageTypeIndicatorEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default MessageTypeIndicatorDetail;

// src/main/webapp/app/entities/message-type-indicator/detail/message-type-indicator-detail.component.ts
import { Component, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatePipe, FormatMediumDatetimePipe } from 'app/shared/date';
import { IMessageTypeIndicator } from '../message-type-indicator.model';

@Component({
  standalone: true,
  selector: 'stp-message-type-indicator-detail',
  templateUrl: './message-type-indicator-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class MessageTypeIndicatorDetailComponent {
  messageTypeIndicator = input<IMessageTypeIndicator | null>(null);

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (messageTypeIndicator(); as messageTypeIndicatorRef) {
      <div>
        <h2 data-cy="messageTypeIndicatorDetailsHeading">
          <span stpTranslate="simulatorApp.messageTypeIndicator.detail.title">Message Type Indicator</span>
        </h2>

        <hr />

        <stp-alert-error></stp-alert-error>

        <stp-alert></stp-alert>

        <dl class="row-md jh-entity-details">
          <dt><span stpTranslate="global.field.id">ID</span></dt>
          <dd>
            <span>{{ messageTypeIndicatorRef.id }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.messageTypeIndicator.name">Name</span></dt>
          <dd>
            <span>{{ messageTypeIndicatorRef.name }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.messageTypeIndicator.code">Code</span></dt>
          <dd>
            <span>{{ messageTypeIndicatorRef.code }}</span>
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span stpTranslate="entity.action.back">Volver</span>
        </button>

        <button type="button" [routerLink]="['/message-type-indicator', messageTypeIndicatorRef.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span stpTranslate="entity.action.edit">Editar</span>
        </button>
      </div>
    }
  </div>
</div>
