// src/main/webapp/app/entities/message-iso-config/message-iso-config.tsx
import React, { useEffect, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { JhiItemCount, JhiPagination, Translate, getPaginationState } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faSort, faSortDown, faSortUp } from '@fortawesome/free-solid-svg-icons';
import { ASC, DESC, ITEMS_PER_PAGE, SORT } from 'app/shared/util/pagination.constants';
import { overridePaginationStateWithQueryParams } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntities } from './message-iso-config.reducer';

export const MessageIsoConfig = () => {
  const dispatch = useAppDispatch();

  const pageLocation = useLocation();
  const navigate = useNavigate();

  const [paginationState, setPaginationState] = useState(
    overridePaginationStateWithQueryParams(getPaginationState(pageLocation, ITEMS_PER_PAGE, 'id'), pageLocation.search),
  );

  const messageIsoConfigList = useAppSelector(state => state.messageIsoConfig.entities);
  const loading = useAppSelector(state => state.messageIsoConfig.loading);
  const totalItems = useAppSelector(state => state.messageIsoConfig.totalItems);

  const getAllEntities = () => {
    dispatch(
      getEntities({
        page: paginationState.activePage - 1,
        size: paginationState.itemsPerPage,
        sort: `${paginationState.sort},${paginationState.order}`,
      }),
    );
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`;
    if (pageLocation.search !== endURL) {
      navigate(`${pageLocation.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  useEffect(() => {
    const params = new URLSearchParams(pageLocation.search);
    const page = params.get('page');
    const sort = params.get(SORT);
    if (page && sort) {
      const sortSplit = sort.split(',');
      setPaginationState({
        ...paginationState,
        activePage: +page,
        sort: sortSplit[0],
        order: sortSplit[1],
      });
    }
  }, [pageLocation.search]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === ASC ? DESC : ASC,
      sort: p,
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage,
    });

  const handleSyncList = () => {
    sortEntities();
  };

  const getSortIconByFieldName = (fieldName: string) => {
    const sortFieldName = paginationState.sort;
    const order = paginationState.order;
    if (sortFieldName !== fieldName) {
      return faSort;
    }
    return order === ASC ? faSortUp : faSortDown;
  };

  return (
    <div>
      <h2 id="message-iso-config-heading" data-cy="MessageIsoConfigHeading">
        <Translate contentKey="simulatorApp.messageIsoConfig.home.title">Message Iso Configs</Translate>
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="simulatorApp.messageIsoConfig.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link
            to="/message-iso-config/new"
            className="btn btn-primary jh-create-entity"
            id="jh-create-entity"
            data-cy="entityCreateButton"
          >
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="simulatorApp.messageIsoConfig.home.createLabel">Create new Message Iso Config</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {messageIsoConfigList && messageIsoConfigList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="simulatorApp.messageIsoConfig.id">ID</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('id')} />
                </th>
                <th className="hand" onClick={sort('name')}>
                  <Translate contentKey="simulatorApp.messageIsoConfig.name">Name</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('name')} />
                </th>
                <th className="hand" onClick={sort('filename')}>
                  <Translate contentKey="simulatorApp.messageIsoConfig.filename">Filename</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('filename')} />
                </th>
                <th>
                  <Translate contentKey="simulatorApp.messageIsoConfig.acquirer">Acquirer</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="simulatorApp.messageIsoConfig.messageTypeIndicator">Message Type Indicator</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {messageIsoConfigList.map((messageIsoConfig, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`/message-iso-config/${messageIsoConfig.id}`} color="link" size="sm">
                      {messageIsoConfig.id}
                    </Button>
                  </td>
                  <td>{messageIsoConfig.name}</td>
                  <td>{messageIsoConfig.filename}</td>
                  <td>
                    {messageIsoConfig.acquirer ? (
                      <Link to={`/acquirer/${messageIsoConfig.acquirer.id}`}>{messageIsoConfig.acquirer.id}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td>
                    {messageIsoConfig.messageTypeIndicator ? (
                      <Link to={`/message-type-indicator/${messageIsoConfig.messageTypeIndicator.id}`}>
                        {messageIsoConfig.messageTypeIndicator.id}
                      </Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button
                        tag={Link}
                        to={`/message-iso-config/${messageIsoConfig.id}`}
                        color="info"
                        size="sm"
                        data-cy="entityDetailsButton"
                      >
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`/message-iso-config/${messageIsoConfig.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                        data-cy="entityEditButton"
                      >
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        onClick={() =>
                          (window.location.href = `/message-iso-config/${messageIsoConfig.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`)
                        }
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="simulatorApp.messageIsoConfig.home.notFound">No Message Iso Configs found</Translate>
            </div>
          )
        )}
      </div>
      {totalItems ? (
        <div className={messageIsoConfigList && messageIsoConfigList.length > 0 ? '' : 'd-none'}>
          <div className="justify-content-center d-flex">
            <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} i18nEnabled />
          </div>
          <div className="justify-content-center d-flex">
            <JhiPagination
              activePage={paginationState.activePage}
              onSelect={handlePagination}
              maxButtons={5}
              itemsPerPage={paginationState.itemsPerPage}
              totalItems={totalItems}
            />
          </div>
        </div>
      ) : (
        ''
      )}
    </div>
  );
};

export default MessageIsoConfig;

// src/main/webapp/app/entities/message-iso-config/list/message-iso-config.component.ts
import { Component, NgZone, OnInit, inject } from '@angular/core';
import { HttpHeaders } from '@angular/common/http';
import { ActivatedRoute, Data, ParamMap, Router, RouterModule } from '@angular/router';
import { Observable, Subscription, combineLatest, filter, tap } from 'rxjs';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import SharedModule from 'app/shared/shared.module';
import { SortByDirective, SortDirective, SortService, type SortState, sortStateSignal } from 'app/shared/sort';
import { DurationPipe, FormatMediumDatePipe, FormatMediumDatetimePipe } from 'app/shared/date';
import { ItemCountComponent } from 'app/shared/pagination';
import { FormsModule } from '@angular/forms';
import { ITEMS_PER_PAGE, PAGE_HEADER, TOTAL_COUNT_RESPONSE_HEADER } from 'app/config/pagination.constants';
import { DEFAULT_SORT_DATA, ITEM_DELETED_EVENT, SORT } from 'app/config/navigation.constants';
import { FilterComponent, FilterOptions, IFilterOption, IFilterOptions } from 'app/shared/filter';
import { IMessageIsoConfig } from '../message-iso-config.model';

import { EntityArrayResponseType, MessageIsoConfigService } from '../service/message-iso-config.service';
import { MessageIsoConfigDeleteDialogComponent } from '../delete/message-iso-config-delete-dialog.component';

@Component({
  standalone: true,
  selector: 'stp-message-iso-config',
  templateUrl: './message-iso-config.component.html',
  imports: [
    RouterModule,
    FormsModule,
    SharedModule,
    SortDirective,
    SortByDirective,
    DurationPipe,
    FormatMediumDatetimePipe,
    FormatMediumDatePipe,
    FilterComponent,
    ItemCountComponent,
  ],
})
export class MessageIsoConfigComponent implements OnInit {
  subscription: Subscription | null = null;
  messageIsoConfigs?: IMessageIsoConfig[];
  isLoading = false;

  sortState = sortStateSignal({});
  filters: IFilterOptions = new FilterOptions();

  itemsPerPage = ITEMS_PER_PAGE;
  totalItems = 0;
  page = 1;

  public readonly router = inject(Router);
  protected readonly messageIsoConfigService = inject(MessageIsoConfigService);
  protected readonly activatedRoute = inject(ActivatedRoute);
  protected readonly sortService = inject(SortService);
  protected modalService = inject(NgbModal);
  protected ngZone = inject(NgZone);

  trackId = (item: IMessageIsoConfig): number => this.messageIsoConfigService.getMessageIsoConfigIdentifier(item);

  ngOnInit(): void {
    this.subscription = combineLatest([this.activatedRoute.queryParamMap, this.activatedRoute.data])
      .pipe(
        tap(([params, data]) => this.fillComponentAttributeFromRoute(params, data)),
        tap(() => this.load()),
      )
      .subscribe();

    this.filters.filterChanges.subscribe(filterOptions => this.handleNavigation(1, this.sortState(), filterOptions));
  }

  delete(messageIsoConfig: IMessageIsoConfig): void {
    const modalRef = this.modalService.open(MessageIsoConfigDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.messageIsoConfig = messageIsoConfig;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed
      .pipe(
        filter(reason => reason === ITEM_DELETED_EVENT),
        tap(() => this.load()),
      )
      .subscribe();
  }

  load(): void {
    this.queryBackend().subscribe({
      next: (res: EntityArrayResponseType) => {
        this.onResponseSuccess(res);
      },
    });
  }

  navigateToWithComponentValues(event: SortState): void {
    this.handleNavigation(this.page, event, this.filters.filterOptions);
  }

  navigateToPage(page: number): void {
    this.handleNavigation(page, this.sortState(), this.filters.filterOptions);
  }

  protected fillComponentAttributeFromRoute(params: ParamMap, data: Data): void {
    const page = params.get(PAGE_HEADER);
    this.page = +(page ?? 1);
    this.sortState.set(this.sortService.parseSortParam(params.get(SORT) ?? data[DEFAULT_SORT_DATA]));
    this.filters.initializeFromParams(params);
  }

  protected onResponseSuccess(response: EntityArrayResponseType): void {
    this.fillComponentAttributesFromResponseHeader(response.headers);
    const dataFromBody = this.fillComponentAttributesFromResponseBody(response.body);
    this.messageIsoConfigs = dataFromBody;
  }

  protected fillComponentAttributesFromResponseBody(data: IMessageIsoConfig[] | null): IMessageIsoConfig[] {
    return data ?? [];
  }

  protected fillComponentAttributesFromResponseHeader(headers: HttpHeaders): void {
    this.totalItems = Number(headers.get(TOTAL_COUNT_RESPONSE_HEADER));
  }

  protected queryBackend(): Observable<EntityArrayResponseType> {
    const { page, filters } = this;

    this.isLoading = true;
    const pageToLoad: number = page;
    const queryObject: any = {
      page: pageToLoad - 1,
      size: this.itemsPerPage,
      sort: this.sortService.buildSortParam(this.sortState()),
    };
    filters.filterOptions.forEach(filterOption => {
      queryObject[filterOption.name] = filterOption.values;
    });
    return this.messageIsoConfigService.query(queryObject).pipe(tap(() => (this.isLoading = false)));
  }

  protected handleNavigation(page: number, sortState: SortState, filterOptions?: IFilterOption[]): void {
    const queryParamsObj: any = {
      page,
      size: this.itemsPerPage,
      sort: this.sortService.buildSortParam(sortState),
    };

    filterOptions?.forEach(filterOption => {
      queryParamsObj[filterOption.nameAsQueryParam()] = filterOption.values;
    });

    this.ngZone.run(() => {
      this.router.navigate(['./'], {
        relativeTo: this.activatedRoute,
        queryParams: queryParamsObj,
      });
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="MessageIsoConfigHeading">
    <span stpTranslate="simulatorApp.messageIsoConfig.home.title">Message Iso Configs</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info me-2" (click)="load()" [disabled]="isLoading">
        <fa-icon icon="sync" [animation]="isLoading ? 'spin' : undefined"></fa-icon>
        <span stpTranslate="simulatorApp.messageIsoConfig.home.refreshListLabel">Refrescar lista</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-message-iso-config"
        [routerLink]="['/message-iso-config/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span stpTranslate="simulatorApp.messageIsoConfig.home.createLabel">Crear nuevo Message Iso Config</span>
      </button>
    </div>
  </h2>

  <stp-alert-error></stp-alert-error>

  <stp-alert></stp-alert>

  <stp-filter [filters]="filters"></stp-filter>

  @if (messageIsoConfigs?.length === 0) {
    <div class="alert alert-warning" id="no-result">
      <span stpTranslate="simulatorApp.messageIsoConfig.home.notFound">Ningún Message Iso Configs encontrado</span>
    </div>
  }

  @if (messageIsoConfigs && messageIsoConfigs.length > 0) {
    <div class="table-responsive table-entities" id="entities">
      <table class="table table-striped" aria-describedby="page-heading">
        <thead>
          <tr stpSort [sortState]="sortState" (sortChange)="navigateToWithComponentValues($event)">
            <th scope="col" stpSortBy="id">
              <div class="d-flex">
                <span stpTranslate="global.field.id">ID</span>

                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col" stpSortBy="name">
              <div class="d-flex">
                <span stpTranslate="simulatorApp.messageIsoConfig.name">Name</span>

                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col" stpSortBy="filename">
              <div class="d-flex">
                <span stpTranslate="simulatorApp.messageIsoConfig.filename">Filename</span>

                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col" stpSortBy="acquirer.id">
              <div class="d-flex">
                <span stpTranslate="simulatorApp.messageIsoConfig.acquirer">Acquirer</span>
                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col" stpSortBy="messageTypeIndicator.id">
              <div class="d-flex">
                <span stpTranslate="simulatorApp.messageIsoConfig.messageTypeIndicator">Message Type Indicator</span>
                <fa-icon class="p-1" icon="sort"></fa-icon>
              </div>
            </th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          @for (messageIsoConfig of messageIsoConfigs; track trackId(messageIsoConfig)) {
            <tr data-cy="entityTable">
              <td>
                <a [routerLink]="['/message-iso-config', messageIsoConfig.id, 'view']">{{ messageIsoConfig.id }}</a>
              </td>
              <td>{{ messageIsoConfig.name }}</td>
              <td>{{ messageIsoConfig.filename }}</td>
              <td>
                @if (messageIsoConfig.acquirer) {
                  <div>
                    <a [routerLink]="['/acquirer', messageIsoConfig.acquirer.id, 'view']">{{ messageIsoConfig.acquirer.id }}</a>
                  </div>
                }
              </td>
              <td>
                @if (messageIsoConfig.messageTypeIndicator) {
                  <div>
                    <a [routerLink]="['/message-type-indicator', messageIsoConfig.messageTypeIndicator.id, 'view']">{{
                      messageIsoConfig.messageTypeIndicator.id
                    }}</a>
                  </div>
                }
              </td>
              <td class="text-end">
                <div class="btn-group">
                  <a
                    [routerLink]="['/message-iso-config', messageIsoConfig.id, 'view']"
                    class="btn btn-info btn-sm"
                    data-cy="entityDetailsButton"
                  >
                    <fa-icon icon="eye"></fa-icon>
                    <span class="d-none d-md-inline" stpTranslate="entity.action.view">Vista</span>
                  </a>

                  <a
                    [routerLink]="['/message-iso-config', messageIsoConfig.id, 'edit']"
                    class="btn btn-primary btn-sm"
                    data-cy="entityEditButton"
                  >
                    <fa-icon icon="pencil-alt"></fa-icon>
                    <span class="d-none d-md-inline" stpTranslate="entity.action.edit">Editar</span>
                  </a>

                  <button type="submit" (click)="delete(messageIsoConfig)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                    <fa-icon icon="times"></fa-icon>
                    <span class="d-none d-md-inline" stpTranslate="entity.action.delete">Eliminar</span>
                  </button>
                </div>
              </td>
            </tr>
          }
        </tbody>
      </table>
    </div>
  }
  @if (messageIsoConfigs && messageIsoConfigs.length > 0) {
    <div>
      <div class="d-flex justify-content-center">
        <stp-item-count [params]="{ page: page, totalItems: totalItems, itemsPerPage: itemsPerPage }"></stp-item-count>
      </div>

      <div class="d-flex justify-content-center">
        <ngb-pagination
          [collectionSize]="totalItems"
          [page]="page"
          [pageSize]="itemsPerPage"
          [maxSize]="5"
          [rotate]="true"
          [boundaryLinks]="true"
          (pageChange)="navigateToPage($event)"
        ></ngb-pagination>
      </div>
    </div>
  }
</div>
