// src/main/webapp/app/entities/message-iso-config/message-iso-config-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Col, Row } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './message-iso-config.reducer';

export const MessageIsoConfigDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const messageIsoConfigEntity = useAppSelector(state => state.messageIsoConfig.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="messageIsoConfigDetailsHeading">
          <Translate contentKey="simulatorApp.messageIsoConfig.detail.title">MessageIsoConfig</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{messageIsoConfigEntity.id}</dd>
          <dt>
            <span id="name">
              <Translate contentKey="simulatorApp.messageIsoConfig.name">Name</Translate>
            </span>
          </dt>
          <dd>{messageIsoConfigEntity.name}</dd>
          <dt>
            <span id="filename">
              <Translate contentKey="simulatorApp.messageIsoConfig.filename">Filename</Translate>
            </span>
          </dt>
          <dd>{messageIsoConfigEntity.filename}</dd>
          <dt>
            <Translate contentKey="simulatorApp.messageIsoConfig.acquirer">Acquirer</Translate>
          </dt>
          <dd>{messageIsoConfigEntity.acquirer ? messageIsoConfigEntity.acquirer.id : ''}</dd>
          <dt>
            <Translate contentKey="simulatorApp.messageIsoConfig.messageTypeIndicator">Message Type Indicator</Translate>
          </dt>
          <dd>{messageIsoConfigEntity.messageTypeIndicator ? messageIsoConfigEntity.messageTypeIndicator.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/message-iso-config" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/message-iso-config/${messageIsoConfigEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default MessageIsoConfigDetail;

// src/main/webapp/app/entities/message-iso-config/detail/message-iso-config-detail.component.ts
import { Component, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatePipe, FormatMediumDatetimePipe } from 'app/shared/date';
import { IMessageIsoConfig } from '../message-iso-config.model';

@Component({
  standalone: true,
  selector: 'stp-message-iso-config-detail',
  templateUrl: './message-iso-config-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class MessageIsoConfigDetailComponent {
  messageIsoConfig = input<IMessageIsoConfig | null>(null);

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (messageIsoConfig(); as messageIsoConfigRef) {
      <div>
        <h2 data-cy="messageIsoConfigDetailsHeading">
          <span stpTranslate="simulatorApp.messageIsoConfig.detail.title">Message Iso Config</span>
        </h2>

        <hr />

        <stp-alert-error></stp-alert-error>

        <stp-alert></stp-alert>

        <dl class="row-md jh-entity-details">
          <dt><span stpTranslate="global.field.id">ID</span></dt>
          <dd>
            <span>{{ messageIsoConfigRef.id }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.messageIsoConfig.name">Name</span></dt>
          <dd>
            <span>{{ messageIsoConfigRef.name }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.messageIsoConfig.filename">Filename</span></dt>
          <dd>
            <span>{{ messageIsoConfigRef.filename }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.messageIsoConfig.acquirer">Acquirer</span></dt>
          <dd>
            @if (messageIsoConfig()!.acquirer) {
              <div>
                <a [routerLink]="['/acquirer', messageIsoConfig()!.acquirer?.id, 'view']">{{ messageIsoConfigRef.acquirer?.id }}</a>
              </div>
            }
          </dd>
          <dt><span stpTranslate="simulatorApp.messageIsoConfig.messageTypeIndicator">Message Type Indicator</span></dt>
          <dd>
            @if (messageIsoConfig()!.messageTypeIndicator) {
              <div>
                <a [routerLink]="['/message-type-indicator', messageIsoConfig()!.messageTypeIndicator?.id, 'view']">{{
                  messageIsoConfigRef.messageTypeIndicator?.id
                }}</a>
              </div>
            }
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span stpTranslate="entity.action.back">Volver</span>
        </button>

        <button type="button" [routerLink]="['/message-iso-config', messageIsoConfigRef.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span stpTranslate="entity.action.edit">Editar</span>
        </button>
      </div>
    }
  </div>
</div>
