// src/main/webapp/app/entities/transaction/transaction-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Col, Row } from 'reactstrap';
import { TextFormat, Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './transaction.reducer';

export const TransactionDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const transactionEntity = useAppSelector(state => state.transaction.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="transactionDetailsHeading">
          <Translate contentKey="simulatorApp.transaction.detail.title">Transaction</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{transactionEntity.id}</dd>
          <dt>
            <span id="date">
              <Translate contentKey="simulatorApp.transaction.date">Date</Translate>
            </span>
          </dt>
          <dd>{transactionEntity.date ? <TextFormat value={transactionEntity.date} type="date" format={APP_DATE_FORMAT} /> : null}</dd>
          <dt>
            <span id="message">
              <Translate contentKey="simulatorApp.transaction.message">Message</Translate>
            </span>
          </dt>
          <dd>{transactionEntity.message}</dd>
          <dt>
            <Translate contentKey="simulatorApp.transaction.transactionType">Transaction Type</Translate>
          </dt>
          <dd>{transactionEntity.transactionType ? transactionEntity.transactionType.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/transaction" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/transaction/${transactionEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default TransactionDetail;

// src/main/webapp/app/entities/transaction/detail/transaction-detail.component.ts
import { Component, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatePipe, FormatMediumDatetimePipe } from 'app/shared/date';
import { ITransaction } from '../transaction.model';

@Component({
  standalone: true,
  selector: 'stp-transaction-detail',
  templateUrl: './transaction-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class TransactionDetailComponent {
  transaction = input<ITransaction | null>(null);

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (transaction(); as transactionRef) {
      <div>
        <h2 data-cy="transactionDetailsHeading"><span stpTranslate="simulatorApp.transaction.detail.title">Transaction</span></h2>

        <hr />

        <stp-alert-error></stp-alert-error>

        <stp-alert></stp-alert>

        <dl class="row-md jh-entity-details">
          <dt><span stpTranslate="global.field.id">ID</span></dt>
          <dd>
            <span>{{ transactionRef.id }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.transaction.date">Date</span></dt>
          <dd>
            <span>{{ transactionRef.date | formatMediumDatetime }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.transaction.message">Message</span></dt>
          <dd>
            <span>{{ transactionRef.message }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.transaction.transactionType">Transaction Type</span></dt>
          <dd>
            @if (transaction()!.transactionType) {
              <div>
                <a [routerLink]="['/transaction-type', transaction()!.transactionType?.id, 'view']">{{
                  transactionRef.transactionType?.id
                }}</a>
              </div>
            }
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span stpTranslate="entity.action.back">Volver</span>
        </button>

        <button type="button" [routerLink]="['/transaction', transactionRef.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span stpTranslate="entity.action.edit">Editar</span>
        </button>
      </div>
    }
  </div>
</div>
