// src/main/webapp/app/entities/account-bank/account-bank-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Col, Row } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './account-bank.reducer';

export const AccountBankDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const accountBankEntity = useAppSelector(state => state.accountBank.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="accountBankDetailsHeading">
          <Translate contentKey="simulatorApp.accountBank.detail.title">AccountBank</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{accountBankEntity.id}</dd>
          <dt>
            <span id="number">
              <Translate contentKey="simulatorApp.accountBank.number">Number</Translate>
            </span>
          </dt>
          <dd>{accountBankEntity.number}</dd>
          <dt>
            <span id="numberIBAN">
              <Translate contentKey="simulatorApp.accountBank.numberIBAN">Number IBAN</Translate>
            </span>
          </dt>
          <dd>{accountBankEntity.numberIBAN}</dd>
          <dt>
            <span id="balance">
              <Translate contentKey="simulatorApp.accountBank.balance">Balance</Translate>
            </span>
          </dt>
          <dd>{accountBankEntity.balance}</dd>
          <dt>
            <Translate contentKey="simulatorApp.accountBank.currency">Currency</Translate>
          </dt>
          <dd>{accountBankEntity.currency ? accountBankEntity.currency.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/account-bank" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/account-bank/${accountBankEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default AccountBankDetail;

// src/main/webapp/app/entities/account-bank/detail/account-bank-detail.component.ts
import { Component, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatePipe, FormatMediumDatetimePipe } from 'app/shared/date';
import { IAccountBank } from '../account-bank.model';

@Component({
  standalone: true,
  selector: 'stp-account-bank-detail',
  templateUrl: './account-bank-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class AccountBankDetailComponent {
  accountBank = input<IAccountBank | null>(null);

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (accountBank(); as accountBankRef) {
      <div>
        <h2 data-cy="accountBankDetailsHeading"><span stpTranslate="simulatorApp.accountBank.detail.title">Account Bank</span></h2>

        <hr />

        <stp-alert-error></stp-alert-error>

        <stp-alert></stp-alert>

        <dl class="row-md jh-entity-details">
          <dt><span stpTranslate="global.field.id">ID</span></dt>
          <dd>
            <span>{{ accountBankRef.id }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.accountBank.number">Number</span></dt>
          <dd>
            <span>{{ accountBankRef.number }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.accountBank.numberIBAN">Number IBAN</span></dt>
          <dd>
            <span>{{ accountBankRef.numberIBAN }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.accountBank.balance">Balance</span></dt>
          <dd>
            <span>{{ accountBankRef.balance }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.accountBank.currency">Currency</span></dt>
          <dd>
            @if (accountBank()!.currency) {
              <div>
                <a [routerLink]="['/currency', accountBank()!.currency?.id, 'view']">{{ accountBankRef.currency?.id }}</a>
              </div>
            }
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span stpTranslate="entity.action.back">Volver</span>
        </button>

        <button type="button" [routerLink]="['/account-bank', accountBankRef.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span stpTranslate="entity.action.edit">Editar</span>
        </button>
      </div>
    }
  </div>
</div>
