// src/main/webapp/app/entities/acquirer/acquirer-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Col, Row } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './acquirer.reducer';

export const AcquirerDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const acquirerEntity = useAppSelector(state => state.acquirer.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="acquirerDetailsHeading">
          <Translate contentKey="simulatorApp.acquirer.detail.title">Acquirer</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{acquirerEntity.id}</dd>
          <dt>
            <span id="name">
              <Translate contentKey="simulatorApp.acquirer.name">Name</Translate>
            </span>
          </dt>
          <dd>{acquirerEntity.name}</dd>
          <dt>
            <span id="socketUrl">
              <Translate contentKey="simulatorApp.acquirer.socketUrl">Socket Url</Translate>
            </span>
          </dt>
          <dd>{acquirerEntity.socketUrl}</dd>
          <dt>
            <span id="email">
              <Translate contentKey="simulatorApp.acquirer.email">Email</Translate>
            </span>
          </dt>
          <dd>{acquirerEntity.email}</dd>
        </dl>
        <Button tag={Link} to="/acquirer" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/acquirer/${acquirerEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default AcquirerDetail;

// src/main/webapp/app/entities/acquirer/detail/acquirer-detail.component.ts
import { Component, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatePipe, FormatMediumDatetimePipe } from 'app/shared/date';
import { IAcquirer } from '../acquirer.model';

@Component({
  standalone: true,
  selector: 'stp-acquirer-detail',
  templateUrl: './acquirer-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class AcquirerDetailComponent {
  acquirer = input<IAcquirer | null>(null);

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (acquirer(); as acquirerRef) {
      <div>
        <h2 data-cy="acquirerDetailsHeading"><span stpTranslate="simulatorApp.acquirer.detail.title">Acquirer</span></h2>

        <hr />

        <stp-alert-error></stp-alert-error>

        <stp-alert></stp-alert>

        <dl class="row-md jh-entity-details">
          <dt><span stpTranslate="global.field.id">ID</span></dt>
          <dd>
            <span>{{ acquirerRef.id }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.acquirer.name">Name</span></dt>
          <dd>
            <span>{{ acquirerRef.name }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.acquirer.socketUrl">Socket Url</span></dt>
          <dd>
            <span>{{ acquirerRef.socketUrl }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.acquirer.email">Email</span></dt>
          <dd>
            <span>{{ acquirerRef.email }}</span>
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span stpTranslate="entity.action.back">Volver</span>
        </button>

        <button type="button" [routerLink]="['/acquirer', acquirerRef.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span stpTranslate="entity.action.edit">Editar</span>
        </button>
      </div>
    }
  </div>
</div>
