// src/main/webapp/app/entities/card/detail/card-detail.component.ts
import { Component, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatePipe, FormatMediumDatetimePipe } from 'app/shared/date';
import { ICard } from '../card.model';

@Component({
  standalone: true,
  selector: 'stp-card-detail',
  templateUrl: './card-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class CardDetailComponent {
  card = input<ICard | null>(null);

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (card(); as cardRef) {
      <div>
        <h2 data-cy="cardDetailsHeading"><span stpTranslate="simulatorApp.card.detail.title">Card</span></h2>

        <hr />

        <stp-alert-error></stp-alert-error>

        <stp-alert></stp-alert>

        <dl class="row-md jh-entity-details">
          <dt><span stpTranslate="global.field.id">ID</span></dt>
          <dd>
            <span>{{ cardRef.id }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.card.number">Number</span></dt>
          <dd>
            <span>{{ cardRef.number }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.card.expirationDate">Expiration Date</span></dt>
          <dd>
            <span>{{ cardRef.expirationDate | formatMediumDate }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.card.verificationValue">Verification Value</span></dt>
          <dd>
            <span>{{ cardRef.verificationValue }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.card.accountBank">Account Bank</span></dt>
          <dd>
            @if (card()!.accountBank) {
              <div>
                <a [routerLink]="['/account-bank', card()!.accountBank?.id, 'view']">{{ cardRef.accountBank?.id }}</a>
              </div>
            }
          </dd>
          <dt><span stpTranslate="simulatorApp.card.cardType">Card Type</span></dt>
          <dd>
            @if (card()!.cardType) {
              <div>
                <a [routerLink]="['/card-type', card()!.cardType?.id, 'view']">{{ cardRef.cardType?.id }}</a>
              </div>
            }
          </dd>
          <dt><span stpTranslate="simulatorApp.card.issuer">Issuer</span></dt>
          <dd>
            @if (card()!.issuer) {
              <div>
                <a [routerLink]="['/issuer', card()!.issuer?.id, 'view']">{{ cardRef.issuer?.id }}</a>
              </div>
            }
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span stpTranslate="entity.action.back">Volver</span>
        </button>

        <button type="button" [routerLink]="['/card', cardRef.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span stpTranslate="entity.action.edit">Editar</span>
        </button>
      </div>
    }
  </div>
</div>

// src/main/webapp/app/entities/card/card-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Col, Row } from 'reactstrap';
import { TextFormat, Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './card.reducer';

export const CardDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const cardEntity = useAppSelector(state => state.card.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="cardDetailsHeading">
          <Translate contentKey="simulatorApp.card.detail.title">Card</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{cardEntity.id}</dd>
          <dt>
            <span id="number">
              <Translate contentKey="simulatorApp.card.number">Number</Translate>
            </span>
          </dt>
          <dd>{cardEntity.number}</dd>
          <dt>
            <span id="expirationDate">
              <Translate contentKey="simulatorApp.card.expirationDate">Expiration Date</Translate>
            </span>
          </dt>
          <dd>
            {cardEntity.expirationDate ? <TextFormat value={cardEntity.expirationDate} type="date" format={APP_LOCAL_DATE_FORMAT} /> : null}
          </dd>
          <dt>
            <span id="verificationValue">
              <Translate contentKey="simulatorApp.card.verificationValue">Verification Value</Translate>
            </span>
          </dt>
          <dd>{cardEntity.verificationValue}</dd>
          <dt>
            <Translate contentKey="simulatorApp.card.accountBank">Account Bank</Translate>
          </dt>
          <dd>{cardEntity.accountBank ? cardEntity.accountBank.id : ''}</dd>
          <dt>
            <Translate contentKey="simulatorApp.card.cardType">Card Type</Translate>
          </dt>
          <dd>{cardEntity.cardType ? cardEntity.cardType.id : ''}</dd>
          <dt>
            <Translate contentKey="simulatorApp.card.issuer">Issuer</Translate>
          </dt>
          <dd>{cardEntity.issuer ? cardEntity.issuer.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/card" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/card/${cardEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default CardDetail;
