// src/main/webapp/app/entities/card-type/card-type-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Col, Row } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './card-type.reducer';

export const CardTypeDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const cardTypeEntity = useAppSelector(state => state.cardType.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="cardTypeDetailsHeading">
          <Translate contentKey="simulatorApp.cardType.detail.title">CardType</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{cardTypeEntity.id}</dd>
          <dt>
            <span id="name">
              <Translate contentKey="simulatorApp.cardType.name">Name</Translate>
            </span>
          </dt>
          <dd>{cardTypeEntity.name}</dd>
        </dl>
        <Button tag={Link} to="/card-type" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/card-type/${cardTypeEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default CardTypeDetail;

// src/main/webapp/app/entities/card-type/detail/card-type-detail.component.ts
import { Component, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatePipe, FormatMediumDatetimePipe } from 'app/shared/date';
import { ICardType } from '../card-type.model';

@Component({
  standalone: true,
  selector: 'stp-card-type-detail',
  templateUrl: './card-type-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class CardTypeDetailComponent {
  cardType = input<ICardType | null>(null);

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (cardType(); as cardTypeRef) {
      <div>
        <h2 data-cy="cardTypeDetailsHeading"><span stpTranslate="simulatorApp.cardType.detail.title">Card Type</span></h2>

        <hr />

        <stp-alert-error></stp-alert-error>

        <stp-alert></stp-alert>

        <dl class="row-md jh-entity-details">
          <dt><span stpTranslate="global.field.id">ID</span></dt>
          <dd>
            <span>{{ cardTypeRef.id }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.cardType.name">Name</span></dt>
          <dd>
            <span>{{ cardTypeRef.name }}</span>
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span stpTranslate="entity.action.back">Volver</span>
        </button>

        <button type="button" [routerLink]="['/card-type', cardTypeRef.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span stpTranslate="entity.action.edit">Editar</span>
        </button>
      </div>
    }
  </div>
</div>
