// src/main/webapp/app/entities/transaction-type/transaction-type-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Col, Row } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './transaction-type.reducer';

export const TransactionTypeDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const transactionTypeEntity = useAppSelector(state => state.transactionType.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="transactionTypeDetailsHeading">
          <Translate contentKey="simulatorApp.transactionType.detail.title">TransactionType</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{transactionTypeEntity.id}</dd>
          <dt>
            <span id="code">
              <Translate contentKey="simulatorApp.transactionType.code">Code</Translate>
            </span>
          </dt>
          <dd>{transactionTypeEntity.code}</dd>
          <dt>
            <span id="name">
              <Translate contentKey="simulatorApp.transactionType.name">Name</Translate>
            </span>
          </dt>
          <dd>{transactionTypeEntity.name}</dd>
        </dl>
        <Button tag={Link} to="/transaction-type" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/transaction-type/${transactionTypeEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default TransactionTypeDetail;

// src/main/webapp/app/entities/transaction-type/detail/transaction-type-detail.component.ts
import { Component, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatePipe, FormatMediumDatetimePipe } from 'app/shared/date';
import { ITransactionType } from '../transaction-type.model';

@Component({
  standalone: true,
  selector: 'stp-transaction-type-detail',
  templateUrl: './transaction-type-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class TransactionTypeDetailComponent {
  transactionType = input<ITransactionType | null>(null);

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (transactionType(); as transactionTypeRef) {
      <div>
        <h2 data-cy="transactionTypeDetailsHeading">
          <span stpTranslate="simulatorApp.transactionType.detail.title">Transaction Type</span>
        </h2>

        <hr />

        <stp-alert-error></stp-alert-error>

        <stp-alert></stp-alert>

        <dl class="row-md jh-entity-details">
          <dt><span stpTranslate="global.field.id">ID</span></dt>
          <dd>
            <span>{{ transactionTypeRef.id }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.transactionType.code">Code</span></dt>
          <dd>
            <span>{{ transactionTypeRef.code }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.transactionType.name">Name</span></dt>
          <dd>
            <span>{{ transactionTypeRef.name }}</span>
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span stpTranslate="entity.action.back">Volver</span>
        </button>

        <button type="button" [routerLink]="['/transaction-type', transactionTypeRef.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span stpTranslate="entity.action.edit">Editar</span>
        </button>
      </div>
    }
  </div>
</div>
