// src/main/webapp/app/entities/merchant/merchant-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Col, Row } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './merchant.reducer';

export const MerchantDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const merchantEntity = useAppSelector(state => state.merchant.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="merchantDetailsHeading">
          <Translate contentKey="simulatorApp.merchant.detail.title">Merchant</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{merchantEntity.id}</dd>
          <dt>
            <span id="name">
              <Translate contentKey="simulatorApp.merchant.name">Name</Translate>
            </span>
          </dt>
          <dd>{merchantEntity.name}</dd>
          <dt>
            <span id="mcc">
              <Translate contentKey="simulatorApp.merchant.mcc">Mcc</Translate>
            </span>
          </dt>
          <dd>{merchantEntity.mcc}</dd>
          <dt>
            <span id="postalCode">
              <Translate contentKey="simulatorApp.merchant.postalCode">Postal Code</Translate>
            </span>
          </dt>
          <dd>{merchantEntity.postalCode}</dd>
          <dt>
            <span id="website">
              <Translate contentKey="simulatorApp.merchant.website">Website</Translate>
            </span>
          </dt>
          <dd>{merchantEntity.website}</dd>
        </dl>
        <Button tag={Link} to="/merchant" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/merchant/${merchantEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default MerchantDetail;

// src/main/webapp/app/entities/merchant/detail/merchant-detail.component.ts
import { Component, input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatePipe, FormatMediumDatetimePipe } from 'app/shared/date';
import { IMerchant } from '../merchant.model';

@Component({
  standalone: true,
  selector: 'stp-merchant-detail',
  templateUrl: './merchant-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class MerchantDetailComponent {
  merchant = input<IMerchant | null>(null);

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (merchant(); as merchantRef) {
      <div>
        <h2 data-cy="merchantDetailsHeading"><span stpTranslate="simulatorApp.merchant.detail.title">Merchant</span></h2>

        <hr />

        <stp-alert-error></stp-alert-error>

        <stp-alert></stp-alert>

        <dl class="row-md jh-entity-details">
          <dt><span stpTranslate="global.field.id">ID</span></dt>
          <dd>
            <span>{{ merchantRef.id }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.merchant.name">Name</span></dt>
          <dd>
            <span>{{ merchantRef.name }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.merchant.mcc">Mcc</span></dt>
          <dd>
            <span>{{ merchantRef.mcc }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.merchant.postalCode">Postal Code</span></dt>
          <dd>
            <span>{{ merchantRef.postalCode }}</span>
          </dd>
          <dt><span stpTranslate="simulatorApp.merchant.website">Website</span></dt>
          <dd>
            <span>{{ merchantRef.website }}</span>
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span stpTranslate="entity.action.back">Volver</span>
        </button>

        <button type="button" [routerLink]="['/merchant', merchantRef.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span stpTranslate="entity.action.edit">Editar</span>
        </button>
      </div>
    }
  </div>
</div>
